# 修改触发的指令
get: 
  - 搜币价
  - 矿难了
off: 
  - 关闭插件
  - 封印
symbolids:
#BTC
  - 1
#LTC
  - 2
#ETH
  - 1027
#XCH
  - 9258
#BABY
  - 10334

symbols:
#BTC
  - BTC
#LTC
  - LTC
#ETH
  - ETH
#XCH
  - XCH
#BABY
  - BABY